### ISSUE TITLE
Error outputting to .css

### ISSUE THREAD

**Issue by julianhutton** [bartvandebiezen/kirby-v2-scssphp#1]
Hi there,

I've just tried to install your SCSS plugin but I'm having some difficulties. I believe I've installed it correctly but it keeps shooting out this error:

Fatal error: Call to undefined function ctype_space() in /Applications/AMPPS/www/s-n/site/plugins/scssphp/scss.inc.php on line 3321

I've renamed the default scss and css files to match my projects in the snippet file—not sure if this has something to do with it? 

Any help would be greatly appreciated.

Julian

**Comment by bartvandebiezen** [comment]
hi @julianhutton,

The plugin will look for 'default.scss' in the /assets/scss/ folder. The css file will be generated automatically. Do you get the same error with the original file names?

Gr. Bart
