### ISSUE TITLE
The each() function is deprecated as of PHP 7.2.0

### ISSUE THREAD

**Issue by mxdvl** [bartvandebiezen/kirby-v2-scssphp#10]
I get an error from `kirby/site/plugins/scssphp/src/Node/Number.php:293`.

````
list($unit, ) = each($units);
````

I solved it by changing the line to the following two:

````
list($unit, ) = [key($units), current($units), 'key' => key($units), 'value' => current($units) ] ;
next($units);
````

I'm not sure that this is an acceptable solution, so could you please confirm that it behaves appropriately? I based my fix on [this StackOverflow answer](https://stackoverflow.com/questions/46492621/how-to-resolve-this-deprecated-function-each-php).

**Comment by bartvandebiezen** [comment]
I updated SCSSPHP to fix the issue.

**Comment by mxdvl** [comment]
Thank you!

Commit for reference: https://github.com/bartvandebiezen/kirby-v2-scssphp/commit/49032d0e306ea9eea198dcda872c4e3cf0cbac9c#diff-ab8bf5815373260f631a736bc7521128L293
