### ISSUE TITLE
Update Plugin to V3

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-scssphp#12]
Hi,
will you update to V3 or should I do it?
It's really easy to update this plugin to v3.

Cheers

**Comment by bartvandebiezen** [comment]
Hi Jan, I planned to do it in the end of April. But of course you are welkom to do so if you need it earlier. 👍

**Comment by janstieler** [comment]
[Pull request](https://github.com/bartvandebiezen/kirby-v2-scssphp/pull/13#issue-257112762)
