### ISSUE TITLE
open_dir error message

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-scssphp#8]
Hi,

On one server I got this error message:
```is_file(): open_basedir restriction in effect. File(../../site/plugins/cookie/cookie.scss.scss) is not within the allowed path(s): …```
but the the path is in the allowed paths. Do you know any security restrictions for open_basedir with `../../`? Because with this relative paths it is possible to go up so that you are in a not allowed path.

Cheers

**Comment by bartvandebiezen** [comment]
Sorry for the late reply 😄 Is this still an issue?

**Comment by janstieler** [comment]
Hi,
ähm I don't know 😄.
I'll close it and if the problem will return I write again.
