### ISSUE TITLE
Problem in the minifyCSS

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-scssphp#9]
Hi,
at the minifyCSS there must be a mistake because for my nested styles like
```
main {
    display: block;
    margin-bottom: 545px;
    & > section {
        &:nth-child(odd) {
            background-color: #fff;
            border-width: 0px;
            .line {
                &:after {
                    background-color: $primary-color;
                }
            }
        }
        &:nth-child(even) {
            background-color: $primary-color;
            .line {
                &:after {
                    background-color: #fff;
                }
            }
        }
    }
}
```
I get `main > section:nth-child(even).line:after` and not `main > section:nth-child(even) .line:after`.
See the space before `.line`.

Cheers

**Comment by 3tlam** [comment]
+1 for that problem.

Quick-fix: disable the minify 
```
// Minify the CSS even further.
require_once $root . '/site/plugins/scssphp/minify.php';
$buffer = minifyCSS($buffer);
```

Better solution:
comment out the lines 33 + 34 in `'/site/plugins/scssphp/minify.php'`
they replace all spaces after opening or closing bracket (and then do a simple fix in 39 + 40 to add it for media queries)
```
$buffer = str_replace(') ', ')', $buffer);
$buffer = str_replace('( ', '(', $buffer);
```

**Comment by mountbatt** [comment]
For me the minification removed  a zero from a font weight call like <code>myfont-latin-700.woff</code> 
the result was always <code>myfont-latin-70.woff</code> 

Solution: comment out line 17 in <code>/site/plugins/scssphp/minify.php</code>
